# netlify.toml
[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/*.pdf"
  [headers.values]
    Content-Type = "application/pdf"

[[headers]]
  for = "/files/*"
  [headers.values]
    Content-Type = "application/pdf"
    Cache-Control = "public, max-age=31536000"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200